export const EMPTY = {
  admissionDetails: {
    registrationType: "IPD",
    ipdNo: "",
    weight: "",
    mlcType: false,
    patientPhoto: null,
    birthAsphyxiaAndNICUShifted: false,
    bloodGroup: "",
    termOfBaby: "",
    modeOfDelivery: "",
    babyIllness: "",
    referredByDoctorId: "",
    referredByDoctorSelectBox: "",
    provisionalDiagnosis: "",
    finalDiagnosis: "",
    operations: "",
    admissionReasonId: "",
    floorId: "",
    bedId: "",
    consultingDoctorId: "",
    laboratorySelectionId: "",
    tpaName: "",
    policyNo: "",
    ccnNo: "",
    insurance: "",
    scheme: "",
    cashType: "",
    freeText: "",
    claimStatus: "",
    finalDiagnosisICDCode: "",
    admissionDate: "",
    admissionTime: "",
    corporation: "",
    relativeDetails: {
      responsiblePerson: "",
      relationship: "",
      relativeContactNo: "",
    },
    covidReport: "",
    vaccinationDetails: "",
    signatureDetails: {
      patientGuardianSign: null,               // <- we’ll fill this from the Signature tab
      interpreterNurseSign: null,
      receptionSign: null,
      relativeWitnessSign: null,
      dischargeInterpreterNurseSign: null,
      dischargePatientGuardianSign: null,
      dischargeRelativeWitnessSign: null,
    },
    height: "",
    otherConsultant: "",
    patientAllergicOrUnderPrecaution: "",
    clinicalDischarge: false,
    billingDischarge: false,
    applicableClass: "",
    paymentRemark: "",
    mlcNo: "",
    employerCompanyName: "",
    TIDNumber: "",
    pharmacyDischarge: false,
    paymentMode: "",
    maintainMRDFileStatus: false,
    patientGuardianDetails: "",
    consultantUnit: "",
    bedDepartment: "",
    patientType: "New",
    patientStatus: "",
    husbandName: "",
    foodPreference: "",
    birthTime: "",
    motherAge: "",
    complaints: "",
    pastFamilyHistory: "",
    remark: "",
    addDietModule: false,
    useClinicalScoreCalculator: false,
    labDischarge: false,
    CPT: "",
    referralFromDoctor: "",
    emergencyNo: "",
    declareAsCriticalPatient: false,
    patientDetail: ""
  },
  identityDetails: {
    patientName: "",
    uhidNo: "",
    salutation: "",
    gender: "",
    age: { years: "", months: "" },
    dateOfBirth: "",
    contactNo: "",
    whatsappNo: "",
    email: "",
    patientReligion: "",
    address: "",
    city: "",
    pinCode: "",
    aadharDetails: {
      aadharNo: "",
      aadharCardFrontImage: null,
      aadharCardBackImage: null,
    },
    panCardDetails: {
      panCardId: "",
      panCardImage: null,
    },
    healthCardDetails: {
      healthCardId: "",
      healthCardImage: null,
    },
  },
};